### ISSUE TITLE
Can't find ipfilter.dll

### ISSUE THREAD

**Issue by anthonywhytuned** [improsec/ImprosecPasswordFilter#1]
Hi,

This looks like a great solution and maybe i'm missing something simple but i'm getting the error that ipfilter.dll isn't being found and it's not showing in the zip file either? Can you advise how to get this file? I've installed the prerequisites.

Many thanks,

Anthony

**Comment by ghost** [comment]
Hi Anthony,

I'm assuming you're experiencing this issue when running the installation script. 

I can see that we have renamed the solution from "ipfilter" to "ipf" and forgotten to modify the (un)installation script accordingly. I've modified the scripts to conform to the new solution name; please try the new scripts in the repository :)

**Comment by anthonywhytuned** [comment]
Hiya,

Thanks for responding :) i'm getting the same error unfortunately.

 Copy-Item -Path "$PSScriptRoot\$filt.dll" -Destination "C:\Windows\System32\$filt.dll" -Force

I think it's this line which is the issue, it's looking for some dll file in the scripts folder but there isn't one included, unless i'm supposed to move the ipf folder into the scripts folder?

Cheers for the help!

Anthony

**Comment by ghost** [comment]
Hi Anthony,

You need to compile the DLL first, and then move it into the same directory as the script :)

Sorry if the instructions were unclear!

**Comment by anthonywhytuned** [comment]
Ahhhhhh that makes sense! Perfect i'll do that. Thanks a lot for your help! :)
